### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by bjornmeansbear** [kevinzweerink/kevinslides#1]
You just working on this for practice, or are you striving to make the most minimum code base slideshow you can? either way I think that's cool, I'm just curious.

**Comment by kevinzweerink** [comment]
Haha I'm just building it for my friend Karen's website. It's been a while since I've made a plugin, but I thought it would be fun to do it. So mostly just messing around. I'm sure it could be cleaned up.

—

**Comment by bjornmeansbear** [comment]
woah this is old. Trying to close out my old issues!
